/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  readonly '/api/model-configs/': {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    /** Read Model Configs */
    readonly get: operations['readModelConfigs']
    readonly put?: never
    /** Create Model Config */
    readonly post: operations['createModelConfig']
    readonly delete?: never
    readonly options?: never
    readonly head?: never
    readonly patch?: never
    readonly trace?: never
  }
  readonly '/api/model-configs/{config_id}': {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    /** Read Model Config */
    readonly get: operations['readModelConfig']
    /** Update Model Config */
    readonly put: operations['updateModelConfig']
    readonly post?: never
    /** Delete Model Config */
    readonly delete: operations['deleteModelConfig']
    readonly options?: never
    readonly head?: never
    readonly patch?: never
    readonly trace?: never
  }
  readonly '/api/model-configs/providers/': {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    /** List Providers */
    readonly get: operations['listProviders']
    readonly put?: never
    readonly post?: never
    readonly delete?: never
    readonly options?: never
    readonly head?: never
    readonly patch?: never
    readonly trace?: never
  }
  readonly '/api/projects/': {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    /** List Projects */
    readonly get: operations['listProjects']
    readonly put?: never
    /** Create Project */
    readonly post: operations['createProject']
    readonly delete?: never
    readonly options?: never
    readonly head?: never
    readonly patch?: never
    readonly trace?: never
  }
  readonly '/api/projects/{project_namespace}/{project_name}': {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    /** Get Project */
    readonly get: operations['getProject']
    readonly put?: never
    readonly post?: never
    /** Delete Project */
    readonly delete: operations['deleteProject']
    readonly options?: never
    readonly head?: never
    readonly patch?: never
    readonly trace?: never
  }
  readonly '/api/projects/{project_namespace}/{project_name}/image': {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    /** Get Project Image */
    readonly get: operations['getProjectImage']
    readonly put?: never
    readonly post?: never
    readonly delete?: never
    readonly options?: never
    readonly head?: never
    readonly patch?: never
    readonly trace?: never
  }
  readonly '/api/sessions/': {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    /** Read Sessions */
    readonly get: operations['readSessions']
    readonly put?: never
    /** Create Session */
    readonly post: operations['createSession']
    readonly delete?: never
    readonly options?: never
    readonly head?: never
    readonly patch?: never
    readonly trace?: never
  }
  readonly '/api/sessions/{session_id}': {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    /** Read Session */
    readonly get: operations['readSession']
    readonly put?: never
    readonly post?: never
    /** Delete Session */
    readonly delete: operations['deleteSession']
    readonly options?: never
    readonly head?: never
    /** Update Session */
    readonly patch: operations['updateSession']
    readonly trace?: never
  }
  readonly '/api/sessions/{session_id}/request': {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    readonly get?: never
    readonly put?: never
    /** Create Model Request */
    readonly post: operations['createModelRequest']
    readonly delete?: never
    readonly options?: never
    readonly head?: never
    readonly patch?: never
    readonly trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * EntityDefinition
     * @description The base class to all story entities.
     */
    readonly EntityDefinition: {
      readonly id: components['schemas']['NormalizedSnakeCase']
      /** Functions */
      readonly functions?: readonly components['schemas']['FunctionDefinition'][] | null
    } & {
      readonly [key: string]: unknown
    }
    /**
     * EntityTypeDefinition
     * @description A definition of a story entity type.
     */
    readonly EntityTypeDefinition: {
      readonly id: components['schemas']['NormalizedPascalCase']
      /** Name */
      readonly name: string
      /** Instructions */
      readonly instructions?: string | null
      /**
       * Traits
       * @default []
       */
      readonly traits: readonly components['schemas']['TraitDefinition'][]
      /** Entities */
      readonly entities: readonly components['schemas']['EntityDefinition'][]
    }
    /** ErrorDetails */
    readonly ErrorDetails: {
      /** Type */
      readonly type: string
      /** Loc */
      readonly loc: readonly (number | string)[]
      /** Msg */
      readonly msg: string
      /** Input */
      readonly input: unknown
      /** Ctx */
      readonly ctx?: {
        readonly [key: string]: unknown
      }
      /** Url */
      readonly url?: string
    }
    /**
     * FinishReason
     * @enum {string}
     */
    readonly FinishReason: 'stop' | 'length' | 'content_filter' | 'tool_call' | 'error'
    /**
     * FunctionDefinition
     * @description A definition of an LLM-called function for the entity.
     */
    readonly FunctionDefinition: {
      /** Target */
      readonly target: string
      /** Name */
      readonly name?: string | null
      /** Description */
      readonly description?: string | null
      /** Properties */
      readonly properties?: {
        readonly [key: string]: string
      } | null
    }
    /** HTTPValidationError */
    readonly HTTPValidationError: {
      /** Detail */
      readonly detail?: readonly components['schemas']['ValidationError'][]
    }
    /**
     * ModelConfig
     * @description A model configuration.
     */
    readonly ModelConfig: {
      /** Name */
      readonly name: string
      readonly provider: components['schemas']['ModelProvider']
      /** Modelname */
      readonly modelName: string
      /** Baseurl */
      readonly baseUrl?: string | null
      /** Apikey */
      readonly apiKey?: string | null
      /** Contextwindow */
      readonly contextWindow: number
      /** Maxtokens */
      readonly maxTokens: number
      /** Temperature */
      readonly temperature: number
      /** Topp */
      readonly topP: number
      /** Presencepenalty */
      readonly presencePenalty: number
      /** Frequencypenalty */
      readonly frequencyPenalty: number
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
    }
    /** ModelConfigCreate */
    readonly ModelConfigCreate: {
      /** Name */
      readonly name: string
      readonly provider: components['schemas']['ModelProvider']
      /** Modelname */
      readonly modelName: string
      /** Baseurl */
      readonly baseUrl?: string | null
      /** Apikey */
      readonly apiKey?: string | null
      /** Contextwindow */
      readonly contextWindow: number
      /** Maxtokens */
      readonly maxTokens: number
      /** Temperature */
      readonly temperature: number
      /** Topp */
      readonly topP: number
      /** Presencepenalty */
      readonly presencePenalty: number
      /** Frequencypenalty */
      readonly frequencyPenalty: number
    }
    /**
     * ModelConfigUpdate
     * @description Update fields for a model config.
     */
    readonly ModelConfigUpdate: {
      /** Name */
      readonly name: string
      readonly provider: components['schemas']['ModelProvider']
      /** Modelname */
      readonly modelName: string
      /** Baseurl */
      readonly baseUrl?: string | null
      /** Apikey */
      readonly apiKey?: string | null
      /** Contextwindow */
      readonly contextWindow: number
      /** Maxtokens */
      readonly maxTokens: number
      /** Temperature */
      readonly temperature: number
      /** Topp */
      readonly topP: number
      /** Presencepenalty */
      readonly presencePenalty: number
      /** Frequencypenalty */
      readonly frequencyPenalty: number
    }
    /**
     * ModelConfigs
     * @description A list of LLM models.
     */
    readonly ModelConfigs: {
      /** Data */
      readonly data: readonly components['schemas']['ModelConfig'][]
      /** Count */
      readonly count: number
    }
    readonly ModelMessage:
      | components['schemas']['ModelRequest']
      | components['schemas']['ModelResponse']
    /**
     * ModelProvider
     * @enum {string}
     */
    readonly ModelProvider:
      | 'anthropic'
      | 'deepseek'
      | 'google'
      | 'mistral'
      | 'ollama'
      | 'openai'
      | 'openai-compatible'
      | 'openrouter'
      | 'xai'
    /** ModelProviderInfo */
    readonly ModelProviderInfo: {
      /** Label */
      readonly label: string
      /** Supports Base Url */
      readonly supports_base_url: boolean
      /** Supports Max Tokens */
      readonly supports_max_tokens: boolean
      /** Supports Temperature */
      readonly supports_temperature: boolean
      /** Supports Top P */
      readonly supports_top_p: boolean
      /** Supports Presence Penalty */
      readonly supports_presence_penalty: boolean
      /** Supports Frequency Penalty */
      readonly supports_frequency_penalty: boolean
      /** Supports Logit Bias */
      readonly supports_logit_bias: boolean
      /** Supports Extra Headers */
      readonly supports_extra_headers: boolean
      /** Supports Extra Body */
      readonly supports_extra_body: boolean
      /** Default Base Url */
      readonly default_base_url?: string | null
    }
    readonly ModelProviderList: {
      readonly [key: string]: components['schemas']['ModelProviderInfo']
    }
    /**
     * ModelProviders
     * @description A list of model providers.
     */
    readonly ModelProviders: components['schemas']['ModelProviderList']
    /**
     * ModelRequest
     * @description A request sent to an LLM.
     */
    readonly ModelRequest: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'request'
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /** Parts */
      readonly parts: readonly components['schemas']['ModelRequestPart'][]
      /**
       * Instructions
       * @default null
       */
      readonly instructions: string | null
    }
    /** ModelRequestCreate */
    readonly ModelRequestCreate: {
      /**
       * Kind
       * @default request
       * @constant
       */
      readonly kind: 'request'
      /** Parts */
      readonly parts: readonly components['schemas']['UserPromptPartCreate'][]
    }
    readonly ModelRequestPart:
      | components['schemas']['UserPromptPart']
      | components['schemas']['ToolReturnPart']
      | components['schemas']['RetryPromptPart']
    /**
     * ModelResponse
     * @description A response from an LLM.
     */
    readonly ModelResponse: {
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'response'
      /** Parts */
      readonly parts: readonly components['schemas']['ModelResponsePart'][]
      /** @default null */
      readonly usage: components['schemas']['Usage'] | null
      /**
       * Modelname
       * @default null
       */
      readonly modelName: string | null
      /**
       * Timestamp
       * Format: date-time
       */
      readonly timestamp: string
      /**
       * Providername
       * @default null
       */
      readonly providerName: string | null
      /** @default null */
      readonly finishReason: components['schemas']['FinishReason'] | null
    }
    readonly ModelResponsePart:
      | components['schemas']['TextPart']
      | components['schemas']['ToolCallPart']
      | components['schemas']['ThinkingPart']
    readonly NormalizedKebabCase: string
    readonly NormalizedPascalCase: string
    readonly NormalizedSnakeCase: string
    /** ProjectBasic */
    readonly ProjectBasic: {
      readonly id: components['schemas']['ProjectId']
      readonly source: components['schemas']['ProjectSource']
      /** Title */
      readonly title: string
      /** Author */
      readonly author?: string | null
      /** Description */
      readonly description?: string | null
      /** Image */
      readonly image?: string | null
    }
    /**
     * ProjectCreate
     * @description Create fields for a project.
     */
    readonly ProjectCreate: {
      readonly id: components['schemas']['ProjectId']
      readonly source: components['schemas']['ProjectSource']
      /** Title */
      readonly title: string
      /** Author */
      readonly author?: string | null
      /** Description */
      readonly description?: string | null
      /** Image */
      readonly image?: string | null
    }
    /** ProjectDetail */
    readonly ProjectDetail: {
      readonly id: components['schemas']['ProjectId']
      readonly source: components['schemas']['ProjectSource']
      /** Title */
      readonly title: string
      /** Author */
      readonly author?: string | null
      /** Description */
      readonly description?: string | null
      /** Image */
      readonly image?: string | null
      /** Entitytypes */
      readonly entityTypes: readonly components['schemas']['EntityTypeDefinition'][]
    }
    readonly ProjectId: string
    /**
     * ProjectSource
     * @enum {string}
     */
    readonly ProjectSource: 'example' | 'local'
    /**
     * Projects
     * @description A list of projects.
     */
    readonly Projects: {
      /** Data */
      readonly data: readonly components['schemas']['ProjectBasic'][]
      /** Count */
      readonly count: number
    }
    /**
     * RetryPromptPart
     * @description A message sent back to an LLM asking it to try again.
     */
    readonly RetryPromptPart: {
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'retry-prompt'
      /** Content */
      readonly content: readonly components['schemas']['ErrorDetails'][] | string
      /**
       * Toolname
       * @default null
       */
      readonly toolName: string | null
      /** Toolcallid */
      readonly toolCallId: string
      /**
       * Timestamp
       * Format: date-time
       */
      readonly timestamp: string
    }
    /** ServerMessage */
    readonly ServerMessage: {
      /** Message */
      readonly message: string
    }
    /**
     * Session
     * @description A chat session with an LLM.
     */
    readonly Session: {
      /** Title */
      readonly title?: string | null
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /** Configid */
      readonly configId?: string | null
      /** Projectid */
      readonly projectId: string
      /**
       * Timestamp
       * Format: date-time
       */
      readonly timestamp?: string
      /** Messagecount */
      readonly messageCount: number
    }
    /**
     * SessionCreate
     * @description Create fields for a session.
     */
    readonly SessionCreate: {
      /** Title */
      readonly title?: string | null
      /**
       * Configid
       * Format: uuid
       */
      readonly configId: string
      /** Projectid */
      readonly projectId: string
    }
    /**
     * SessionFull
     * @description A chat session with an LLM including the message history.
     */
    readonly SessionFull: {
      /** Title */
      readonly title?: string | null
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /** Configid */
      readonly configId?: string | null
      /** Projectid */
      readonly projectId: string
      /**
       * Timestamp
       * Format: date-time
       */
      readonly timestamp?: string
      /** Messagecount */
      readonly messageCount: number
      /** Messages */
      readonly messages: readonly components['schemas']['ModelMessage'][]
    }
    /**
     * SessionUpdate
     * @description Update fields for a session.
     */
    readonly SessionUpdate: {
      /** Title */
      readonly title?: string | null
      /** Configid */
      readonly configId?: string | null
    }
    /**
     * Sessions
     * @description A list of sessions.
     */
    readonly Sessions: {
      /** Data */
      readonly data: readonly components['schemas']['Session'][]
      /** Count */
      readonly count: number
    }
    /**
     * TextPart
     * @description A plain text response from an LLM.
     */
    readonly TextPart: {
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /**
       * Timestamp
       * Format: date-time
       */
      readonly timestamp: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'text'
      /** Content */
      readonly content: string
    }
    /**
     * ThinkingPart
     * @description A thinking response from an LLM.
     */
    readonly ThinkingPart: {
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /**
       * Timestamp
       * Format: date-time
       */
      readonly timestamp: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'thinking'
      /** Content */
      readonly content: string
      /**
       * Providername
       * @default null
       */
      readonly providerName: string | null
      /**
       * Durationseconds
       * @default null
       */
      readonly durationSeconds: number | null
    }
    /**
     * ToolCallPart
     * @description A tool call from an LLM.
     */
    readonly ToolCallPart: {
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /**
       * Timestamp
       * Format: date-time
       */
      readonly timestamp: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'tool-call'
      /** Toolname */
      readonly toolName: string
      /**
       * Args
       * @default null
       */
      readonly args: string | null
      /** Toolcallid */
      readonly toolCallId: string
    }
    /**
     * ToolReturnPart
     * @description A tool return message, this encodes the result of running a tool.
     */
    readonly ToolReturnPart: {
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'tool-return'
      /** Toolname */
      readonly toolName: string | null
      /** Content */
      readonly content: string
      /** Toolcallid */
      readonly toolCallId: string | null
      /** Timestamp */
      readonly timestamp: string | null
    }
    /** TraitDefinition */
    readonly TraitDefinition: {
      readonly name: components['schemas']['NormalizedSnakeCase']
      /** Options */
      readonly options?: {
        readonly [key: string]: unknown
      }
    }
    /** Usage */
    readonly Usage: {
      /** Inputtokens */
      readonly inputTokens: number
      /** Outputtokens */
      readonly outputTokens: number
      /** Cachewritetokens */
      readonly cacheWriteTokens: number
      /** Cachereadtokens */
      readonly cacheReadTokens: number
    }
    /**
     * UserPromptPart
     * @description A user prompt, generally written by the user.
     */
    readonly UserPromptPart: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'user-prompt'
      /** Content */
      readonly content: string
      /**
       * Id
       * Format: uuid
       */
      readonly id: string
      /**
       * Timestamp
       * Format: date-time
       */
      readonly timestamp: string
    }
    /** UserPromptPartCreate */
    readonly UserPromptPartCreate: {
      /**
       * Kind
       * @default user-prompt
       * @constant
       */
      readonly kind: 'user-prompt'
      /** Content */
      readonly content: string
      /**
       * Timestamp
       * Format: date-time
       */
      readonly timestamp?: string
    }
    /** ValidationError */
    readonly ValidationError: {
      /** Location */
      readonly loc: readonly (string | number)[]
      /** Message */
      readonly msg: string
      /** Error Type */
      readonly type: string
      /** Input */
      readonly input?: unknown
      /** Context */
      readonly ctx?: Record<string, never>
    }
    /** ContentDelta */
    readonly ContentDelta: {
      /** Content */
      readonly content: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'content'
    }
    readonly Delta:
      | components['schemas']['ContentDelta']
      | components['schemas']['ToolArgsDelta']
      | components['schemas']['ToolNameDelta']
    /** ToolArgsDelta */
    readonly ToolArgsDelta: {
      /** Args */
      readonly args: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'tool_args'
    }
    /** ToolNameDelta */
    readonly ToolNameDelta: {
      /** Toolname */
      readonly toolName: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'tool_name'
    }
    /**
     * WebSocketErrorMessage
     * @description An error notification.
     */
    readonly WebSocketErrorMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'error'
      /**
       * Sessionid
       * @default null
       */
      readonly sessionId: string | null
      /** Name */
      readonly name: string
      /** Message */
      readonly message: string
    }
    /**
     * WebSocketPongMessage
     * @description An answer to a client ping.
     */
    readonly WebSocketPongMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'pong'
    }
    /**
     * WebSocketStreamMessageMessage
     * @description A streaming message update.
     */
    readonly WebSocketStreamMessageMessage: {
      /**
       * Sessionid
       * Format: uuid
       */
      readonly sessionId: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'stream_message'
      readonly message: components['schemas']['ModelMessage']
    }
    /**
     * WebSocketStreamPartDeltaMessage
     * @description A streaming part delta update.
     */
    readonly WebSocketStreamPartDeltaMessage: {
      /**
       * Sessionid
       * Format: uuid
       */
      readonly sessionId: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'stream_part_delta'
      /**
       * Messageid
       * Format: uuid
       */
      readonly messageId: string
      /**
       * Partid
       * Format: uuid
       */
      readonly partId: string
      readonly delta: components['schemas']['Delta']
    }
    /**
     * WebSocketStreamPartMessage
     * @description A streaming part update.
     */
    readonly WebSocketStreamPartMessage: {
      /**
       * Sessionid
       * Format: uuid
       */
      readonly sessionId: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'stream_part'
      /**
       * Messageid
       * Format: uuid
       */
      readonly messageId: string
      readonly part: components['schemas']['ModelResponsePart']
    }
    /**
     * WebSocketStreamStatusMessage
     * @description A status update.
     */
    readonly WebSocketStreamStatusMessage: {
      /**
       * Sessionid
       * Format: uuid
       */
      readonly sessionId: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'stream_status'
      /**
       * Status
       * @enum {string}
       */
      readonly status: 'started' | 'stopped'
    }
    readonly WebSocketServerMessage:
      | components['schemas']['WebSocketPongMessage']
      | components['schemas']['WebSocketErrorMessage']
      | components['schemas']['WebSocketStreamStatusMessage']
      | components['schemas']['WebSocketStreamMessageMessage']
      | components['schemas']['WebSocketStreamPartMessage']
      | components['schemas']['WebSocketStreamPartDeltaMessage']
    /** WebSocketDummyMessage */
    readonly WebSocketDummyMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'dummy'
    }
    /**
     * WebSocketPingMessage
     * @description A ping message.
     */
    readonly WebSocketPingMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly kind: 'ping'
    }
    readonly WebSocketClientMessage:
      | components['schemas']['WebSocketPingMessage']
      | components['schemas']['WebSocketDummyMessage']
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  readonly readModelConfigs: {
    readonly parameters: {
      readonly query?: {
        readonly skip?: number
        readonly limit?: number
      }
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ModelConfigs']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly createModelConfig: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['ModelConfigCreate']
      }
    }
    readonly responses: {
      /** @description Successful Response */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ModelConfig']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly readModelConfig: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly config_id: string
      }
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ModelConfig']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly updateModelConfig: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly config_id: string
      }
      readonly cookie?: never
    }
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['ModelConfigUpdate']
      }
    }
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ServerMessage']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly deleteModelConfig: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly config_id: string
      }
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ServerMessage']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly listProviders: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ModelProviders']
        }
      }
    }
  }
  readonly listProjects: {
    readonly parameters: {
      readonly query?: {
        readonly source?: components['schemas']['ProjectSource'] | null
      }
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['Projects']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly createProject: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['ProjectCreate']
      }
    }
    readonly responses: {
      /** @description Successful Response */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ProjectBasic']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly getProject: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly project_namespace: components['schemas']['NormalizedKebabCase']
        readonly project_name: components['schemas']['NormalizedKebabCase']
      }
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ProjectDetail']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly deleteProject: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly project_namespace: components['schemas']['NormalizedKebabCase']
        readonly project_name: components['schemas']['NormalizedKebabCase']
      }
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ServerMessage']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly getProjectImage: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly project_namespace: components['schemas']['NormalizedKebabCase']
        readonly project_name: components['schemas']['NormalizedKebabCase']
      }
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': unknown
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly readSessions: {
    readonly parameters: {
      readonly query?: {
        readonly project_id?: string | null
        readonly skip?: number
        readonly limit?: number
      }
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['Sessions']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly createSession: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path?: never
      readonly cookie?: never
    }
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['SessionCreate']
      }
    }
    readonly responses: {
      /** @description Successful Response */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['Session']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly readSession: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly session_id: string
      }
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['SessionFull']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly deleteSession: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly session_id: string
      }
      readonly cookie?: never
    }
    readonly requestBody?: never
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ServerMessage']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly updateSession: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly session_id: string
      }
      readonly cookie?: never
    }
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['SessionUpdate']
      }
    }
    readonly responses: {
      /** @description Successful Response */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ServerMessage']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  readonly createModelRequest: {
    readonly parameters: {
      readonly query?: never
      readonly header?: never
      readonly path: {
        readonly session_id: string
      }
      readonly cookie?: never
    }
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['ModelRequestCreate']
      }
    }
    readonly responses: {
      /** @description Successful Response */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['ModelRequest']
        }
      }
      /** @description Validation Error */
      readonly 422: {
        headers: {
          readonly [name: string]: unknown
        }
        content: {
          readonly 'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
