/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/chats/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read Chats */
    get: operations['read_chats_api_chats__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/chats/{chat_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read Chat */
    get: operations['read_chat_api_chats__chat_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/chats/new': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Chat */
    post: operations['create_chat_api_chats_new_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ChatCreate */
    ChatCreate: {
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string
    }
    /** ChatListPublic */
    ChatListPublic: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
    }
    /** ChatPublic */
    ChatPublic: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Messages */
      messages: components['schemas']['MessageListPublic'][]
    }
    /** ChatsPublic */
    ChatsPublic: {
      /** Data */
      data: components['schemas']['ChatListPublic'][]
      /** Count */
      count: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** MessageListPublic */
    MessageListPublic: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      sender: components['schemas']['Sender']
      /** Thinking */
      thinking: string | null
      /** Text */
      text: string
    }
    /**
     * Sender
     * @enum {string}
     */
    Sender: 'human' | 'llm'
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  read_chats_api_chats__get: {
    parameters: {
      query?: {
        skip?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChatsPublic']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_chat_api_chats__chat_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        chat_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChatPublic']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_chat_api_chats_new_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChatPublic']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
